delay = 180
changerate = 0.0087
download_photos = true
message = """
$id $productName
$productURL ¥$price (USD $priceCurrency)
"""

[[searches]]
keywords = "ポケットモンスター 緑 GB"
price_max = 7000

[[searches]]
keywords = "レイディアントシルバーガン セガサターン"
price_max = 15000

[[searches]]
keywords = "ピカチュウ ニンテンドー64"
price_max = 13000

[[searches]]
keywords = "サムライスピリッツ ネオジオ"
price_max = 11000

[[searches]]
keywords = "餓狼伝説 ネオジオ"
price_max = 11000

[[searches]]
keywords = "ゼルダ ディスクシステム"
price_max = 7000

[telegram]
token = "8937876728:AAEYasoXKcmCMiQn3308fjCMcLyrgak4JJQ"
chat_id = 8258920049
